### ISSUE TITLE
Allow specifying extra parameters to `fig.savefig` in `CockpitPlotter.plot`

### ISSUE THREAD

**Issue by mseitzer** [f-dangel/cockpit#10]
## Description

I suggest to extend `CockpitPlotter.plot` such that a keyword dictionary can be passed to it specifying parameters to `fig.savefig`. This is to be able to choose 1) a DPI value or 2) a different file format (e.g. PDF). 

Currently, the stored image files have a poor resolution and thus are not very readable. Being able to choose a DPI value or saving to PDF would fix this issue.

**Comment by fsschneider** [comment]
Hi,

this seems like a good idea!

Could you have a look at the `savefig_handeling` branch where I tried to address this? Specifically, I now added a `savefig_kwargs` argument to the `CockpitPlotter.plot` function.

https://github.com/f-dangel/cockpit/blob/67257a68cd55e4c3dfa83875aaddab72cd1e02bb/cockpit/plotter.py#L61-L75

@f-dangel Could you also have a look over my changes?

**Comment by f-dangel** [comment]
Yap, I can review a PR once it's ready.

**Comment by mseitzer** [comment]
Looks good to me :+1:

**Comment by fsschneider** [comment]
Should be solved with #16.
