### ISSUE TITLE
Visual bugs when plotting: overlapping text.

### ISSUE THREAD

**Issue by mseitzer** [f-dangel/cockpit#11]
## Description

Some elements of the produced plots are overlapping, resulting in suboptimal readability. See the attached plot. 
![cockpit__primary](https://user-images.githubusercontent.com/16725193/126351248-1ec4555a-e918-44c7-933a-e1a1d7372795.png)

**Comment by fsschneider** [comment]
I am afraid there is not a lot I can do here.

We make heavy use of combined plots. For them, I found it really tricky to not result in overlapping text, labels, etc. I already spend quite some time trying to improve it, but unfortunately, there are still situations where texts or labels overlap.

If anyone has an idea on how to improve this, I am happy to give it another try.

Note, that you can always look into the `fig` property of the `CockpitPlotter`. This gives you control over all elements of the plot. That way you can at least improve the layout "manually" once you have the plot.

**Comment by mseitzer** [comment]
I understand, this is probably difficult to get correct in all cases. It also seems to depend on screen resolution -- on another screen, I had less overlap. I will close this issue then.
