### ISSUE TITLE
Monai 3D Resnet models

### ISSUE THREAD

**Issue by Mushtaqml** [f-dangel/cockpit#21]
Hi!

Thank you for this project, indeed it is quite interesting work. 

I am curious to know that if we can use it to interpret/observe the training of a 3D resnet model? 

Regards

**Comment by f-dangel** [comment]
Hi,

thanks for your question. As many of Cockpit's quantities rely on BackPACK, your model architecture must be supported to get the full view. You can take a look at the supported layers [here](https://docs.backpack.pt/en/master/supported-layers.html).

If your model is not supported by BackPACK, you can still configure a `Cockpit` with quantities that rely purely on PyTorch's autodiff. To do that, you can tweak the [advanced exampe](https://cockpit.readthedocs.io/en/latest/examples/02_advanced_fmnist.html) from the docs.

Best,
Felix

**Comment by Mushtaqml** [comment]
@f-dangel Thank you for the response. 

As it is a resnet model, I don't think BackPACK supports it. I am looking into the advanced example, and will update you in a while, if it works.

**Comment by f-dangel** [comment]
Sounds good.

 By the way, BackPACK has basic support for ResNets from version `1.4.0` on. Check out [this example](https://docs.backpack.pt/en/1.4.0/use_cases/example_resnet_all_in_one.html#any-resnet-with-backpack-s-converter) to see how it works.

**Comment by fsschneider** [comment]
I am closing this issue as it is stale. Please feel free to open it again if you have further questions.
