### ISSUE TITLE
Plots from remote machine

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [f-dangel/cockpit#27]
I am running some experiments on a remote machine, and I can't see any cockpit plot. 
I have the same problem when running the basic example.
Is there a way of solving this? Am I missing something?

This may be a dumb question, sorry I am quite new to this.

Thank you!

**Comment by fsschneider** [comment]
Hi, thanks for asking this question.

As a first test, could you tell Cockpit to save the image to disk (see https://cockpit.readthedocs.io/en/latest/api/plotter.html, there is the options to `save_plot` with a `savedir`).
You could then transfer the stored Cockpit plot in whatever way you use to transfer files from your remote machine.

This way we know that Cockpit is running as it should and is indeed producing plots.

**Comment by Niccolo-Ajroldi** [comment]
Thank you @fsschneider 
That's exactly what I am doing so far, I wanted to know if there is a way to visualize the plots live.
Thank you anyway!

**Comment by fsschneider** [comment]
Got it!
There are no special features in Cockpit supporting this as I don't think this is a Cockpit-specific issue.
However, I believe, this should be possible via X11 forwarding, see https://stackoverflow.com/questions/3453188/matplotlib-display-plot-on-a-remote-machine

**Comment by Niccolo-Ajroldi** [comment]
Thank you for the useful reference. Really appreciate it!
